### ISSUE TITLE
Use GPIO interrupt instead of polling GPIO

### ISSUE THREAD

**Issue by cyberman54** [spacehuhn/SimpleButton#3]
Would it improve performance to not read the GPIO by polling it in the arduino loop, but to have an interrupt attached to the button, and read it after the interrupt fires?

How could that be done?

**Comment by spacehuhn** [comment]
Yes it would! This library needs some clean up anyway.
I will include that when I have time to update the library.

**Comment by cyberman54** [comment]
Allright, i got this already running.
Just calling `b->update()` from an interrupt handler, which is notified by an ISR which triggers on button press by hardware irq. So no `loop()` required.
